<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="COS-874531-L1" failures="1" tests="9" name="FUnctionalTest" time="0.109" errors="0" timestamp="15 May 2018 19:56:07 GMT">
  <testcase classname="teststart.Test3" name="Demo4" time="0.016"/>
  <testcase classname="teststart.Test3" name="Demo5" time="0.0"/>
  <testcase classname="teststart.Test3" name="Demo6" time="0.0"/>
  <testcase classname="teststart.Test3" name="Demo6" time="0.0"/>
  <testcase classname="teststart.Test3" name="Demo6" time="0.015"/>
  <testcase classname="teststart.Test4" name="Demo10" time="0.0"/>
  <testcase classname="teststart.Test4" name="Demo11" time="0.016"/>
  <testcase classname="teststart.Test4" name="Demo8" time="0.0"/>
  <testcase classname="teststart.Test3" name="Demo7" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at teststart.Test3.Demo7(Test3.java:33)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- Demo7 -->
  <testcase classname="teststart.Test4" name="Demo9" time="0.0">
    <ignored/>
  </testcase> <!-- Demo9 -->
</testsuite> <!-- FUnctionalTest -->
